[package]
name = "bench-arkworks"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.3.0"
ark-ff = { version = "0.3.0", features = [ "asm" ] }
ark-std = "0.3.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "invmul"
harness = false